apiVersion: v1
kind: Service
metadata:
    name: lb-app-01
spec:
    selector:
        app: app-01
    type: LoadBalancer
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
          nodePort: 30002
